#! /bin/bash

# Exit if any subcommand fails
set -e
set -o pipefail

if command -v docker-compose > /dev/null; then
  docker-compose build
  docker-compose run app shards install
elif command -v docker compose > /dev/null; then
  docker compose build
  docker compose run app shards install
else
  printf 'Docker and/or docker-compose are not installed.\n'
  printf 'See https://docs.docker.com/compose/install/ for install instructions.\n'
  exit 1
fi

