#! /bin/bash

# Exit if any subcommand fails
set -e
set -o pipefail

if command -v docker compose > /dev/null; then
  docker compose build
  docker compose run app shards install
else
  printf 'Command docker compose does not exist. Install Docker.\n'
  printf 'See https://docs.docker.com/compose/install/ for install instructions.\n'
  exit 1
fi

