#! /bin/bash

# Exit if any subcommand fails
set -e
set -o pipefail

if command -v docker-compose > /dev/null; then
  COMPOSE="docker-compose run app"
elif command -v docker compose > /dev/null; then
  COMPOSE="docker compose run app"
fi

printf "\nrunning specs with 'crystal spec'\n\n"
$COMPOSE crystal spec
printf "\nformatting code with 'crystal tool format --check'\n\n"
$COMPOSE crystal tool format --check
