#! /bin/bash

# Exit if any subcommand fails
set -e
set -o pipefail

COMPOSE="docker-compose run app"

printf "\nrunning specs with 'crystal spec --no-debug'\n\n"
$COMPOSE crystal spec --no-debug
printf "\nformatting code with 'crystal tool format src spec'\n\n"
$COMPOSE crystal tool format src spec
