name: Lucky Flow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: "*"

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crystal-lang/install-crystal@v1
      - run: shards install
      - run: crystal tool format --check
      - run: ./bin/ameba
  webless_specs:
    strategy:
      matrix:
        crystal_version:
          - 1.0.0
          - latest
          - nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal_version}}
      - run: shards install
      - run: LUCKYFLOW_DRIVER=webless crystal spec --tag ~headless_chrome
  selenium_specs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crystal-lang/install-crystal@v1
      - run: shards install
      - run: LUCKYFLOW_DRIVER=headless_chrome crystal spec
  
